# Generated by Django 4.2.30 on 2026-09-23 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KopyaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('alpha', models.FloatField()),
                ('input_hash', models.CharField(max_length=32)),
                ('result', models.BinaryField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Kopya Analiz Sonucu',
                'verbose_name_plural': 'Kopya Analiz Sonuçları',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='KopyaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('file', models.FileField(upload_to='kopya/uploads/', verbose_name='Excel dosyası')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Dosya adı')),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kopya_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Kopya Excel Yüklemesi',
                'verbose_name_plural': 'Kopya Excel Yüklemeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='kopyaanalysis',
            constraint=models.UniqueConstraint(fields=('source_id', 'alpha', 'input_hash'), name='kopya_analysis_unique_key'),
        ),
    ]
