# Generated by Django 4.2.30 on 2026-09-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptikBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(default='CREATED', max_length=32)),
                ('data', models.JSONField(default=dict, verbose_name='Batch verisi')),
                ('scores', models.JSONField(blank=True, null=True, verbose_name='Puanlama sonucu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Optik Batch',
                'verbose_name_plural': "Optik Batch'ler",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptikTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('course_code', models.CharField(blank=True, max_length=50, verbose_name='Ders Kodu')),
                ('course_name', models.CharField(blank=True, max_length=255, verbose_name='Ders Adı')),
                ('exam_type', models.CharField(blank=True, max_length=100, verbose_name='Sınav Türü')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='Akademik Yıl')),
                ('semester', models.CharField(blank=True, max_length=20, verbose_name='Dönem')),
                ('is_approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict, verbose_name='Test verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optik_tests', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Optik Test',
                'verbose_name_plural': 'Optik Testler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptikSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('metadata', models.JSONField(default=dict)),
                ('records', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='optik.optikbatch')),
            ],
            options={
                'verbose_name': 'Optik Snapshot',
                'verbose_name_plural': "Optik Snapshot'lar",
                'ordering': ['batch', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptikRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('student_no', models.CharField(blank=True, db_index=True, max_length=32)),
                ('booklet', models.CharField(blank=True, max_length=8)),
                ('data', models.JSONField(default=dict, verbose_name='Kayıt verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='optik.optikbatch')),
            ],
            options={
                'verbose_name': 'Optik Kayıt',
                'verbose_name_plural': 'Optik Kayıtlar',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='optikbatch',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='optik.optiktest'),
        ),
        migrations.AddConstraint(
            model_name='optiksnapshot',
            constraint=models.UniqueConstraint(fields=('batch', 'version'), name='optik_snapshot_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='optikrecord',
            constraint=models.UniqueConstraint(fields=('batch', 'record_id'), name='optik_record_unique_in_batch'),
        ),
    ]
