# Generated by Django 6.0.1 on 2026-01-12 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: "Optik Okuyucu v1", "Scantron 2000"', max_length=100, verbose_name='Format Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('format_type', models.CharField(choices=[('FIXED_WIDTH', 'Sabit Genişlik'), ('DELIMITED', 'Ayraçlı')], default='FIXED_WIDTH', max_length=20, verbose_name='Format Tipi')),
                ('delimiter', models.CharField(blank=True, default='', help_text='Ayraçlı format için: ; , \\t (tab için \\t yazın)', max_length=10, verbose_name='Ayraç')),
                ('student_no_start', models.IntegerField(default=0, help_text='0-indexed karakter pozisyonu', verbose_name='Öğrenci No Başlangıç')),
                ('student_no_end', models.IntegerField(default=12, help_text='0-indexed karakter pozisyonu (dahil değil)', verbose_name='Öğrenci No Bitiş')),
                ('student_name_start', models.IntegerField(default=15, verbose_name='Ad Soyad Başlangıç')),
                ('student_name_end', models.IntegerField(default=38, verbose_name='Ad Soyad Bitiş')),
                ('answers_start', models.IntegerField(default=38, verbose_name='Cevaplar Başlangıç')),
                ('answers_end', models.IntegerField(blank=True, help_text='Boş bırakılırsa satır sonuna kadar okunur', null=True, verbose_name='Cevaplar Bitiş')),
                ('has_booklet_field', models.BooleanField(default=False, verbose_name='Kitapçık Alanı Var mı?')),
                ('booklet_start', models.IntegerField(blank=True, null=True, verbose_name='Kitapçık Başlangıç')),
                ('booklet_end', models.IntegerField(blank=True, null=True, verbose_name='Kitapçık Bitiş')),
                ('key_identifier', models.CharField(default='ANAHTAR', help_text='Cevap anahtarını tanımlayan metin. Örn: ANAHTAR, CEVAP, 000000000000', max_length=50, verbose_name='Anahtar Tanımlayıcı')),
                ('key_identifier_field', models.CharField(choices=[('student_no', 'Öğrenci No'), ('student_name', 'Ad Soyad')], default='student_name', max_length=20, verbose_name='Anahtar Aranacak Alan')),
                ('valid_options', models.CharField(default='ABCDE', help_text='Örn: ABCDE veya ABCD', max_length=20, verbose_name='Geçerli Şıklar')),
                ('blank_markers', models.CharField(default='-* .', help_text='Boş cevabı temsil eden karakterler. Örn: -* .', max_length=20, verbose_name='Boş İşaretleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, help_text='Yeni yüklemelerde varsayılan olarak seçilsin', verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Dosya Formatı',
                'verbose_name_plural': 'Dosya Formatları',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('processing_status', models.CharField(choices=[('QUEUED', 'Kuyrukta'), ('PROCESSING', 'İşleniyor'), ('PROCESSED', 'İşlendi'), ('FAILED', 'Başarısız')], default='QUEUED', max_length=20, verbose_name='Durum')),
                ('question_count', models.IntegerField(blank=True, null=True, verbose_name='Soru Sayısı')),
                ('student_count', models.IntegerField(blank=True, null=True, verbose_name='Öğrenci Sayısı')),
                ('error_count', models.IntegerField(default=0, verbose_name='Hata Sayısı')),
                ('has_multiple_keys', models.BooleanField(default=False, verbose_name='Çoklu Anahtar')),
                ('error_summary', models.TextField(blank=True, verbose_name='Hata Özeti')),
                ('file_format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.fileformatconfig', verbose_name='Dosya Formatı')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Yükleme Oturumu',
                'verbose_name_plural': 'Yükleme Oturumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(blank=True, max_length=50, verbose_name='Öğrenci No')),
                ('student_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('booklet', models.CharField(blank=True, max_length=10, verbose_name='Kitapçık')),
                ('answers_raw', models.TextField(verbose_name='Ham Cevaplar')),
                ('row_number_in_file', models.IntegerField(verbose_name='Satır No')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Doğru')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Yanlış')),
                ('blank_count', models.IntegerField(default=0, verbose_name='Boş')),
                ('invalid_count', models.IntegerField(default=0, verbose_name='Geçersiz')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Puan')),
                ('detailed_results', models.TextField(blank=True, help_text='Her soru için D(oğru)/Y(anlış)/B(oş)/G(eçersiz)', verbose_name='Detaylı Sonuçlar')),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grading.uploadsession', verbose_name='Yükleme Oturumu')),
            ],
            options={
                'verbose_name': 'Öğrenci Sonucu',
                'verbose_name_plural': 'Öğrenci Sonuçları',
                'ordering': ['row_number_in_file'],
            },
        ),
        migrations.CreateModel(
            name='ParsingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(verbose_name='Satır No')),
                ('raw_line', models.TextField(verbose_name='Ham Satır')),
                ('message', models.CharField(max_length=500, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_errors', to='grading.uploadsession', verbose_name='Yükleme Oturumu')),
            ],
            options={
                'verbose_name': 'Ayrıştırma Hatası',
                'verbose_name_plural': 'Ayrıştırma Hataları',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylı'), ('REJECTED', 'Reddedildi'), ('SUSPENDED', 'Askıya Alındı')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('note', models.TextField(blank=True, help_text='Admin tarafından eklenen not', verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
