# Generated by Django 4.2.27 on 2026-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='answer_key',
            field=models.TextField(blank=True, verbose_name='Cevap Anahtarı'),
        ),
    ]
