# Generated by Django 4.2.27 on 2026-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_uploadsession_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='wrong_to_correct_ratio',
            field=models.IntegerField(blank=True, default=0, help_text='Kaç yanlış bir doğruyu götürür? (Örn: 4)', null=True, verbose_name='Yanlış Doğru Oranı'),
        ),
    ]
