# Generated by Django 4.2.27 on 2026-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_uploadsession_wrong_to_correct_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net'),
        ),
    ]
