# Generated by Django 4.2.27 on 2026-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_studentresult_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='points_per_question',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Her bir netin kaç puan değerinde olduğu (Örn: 1.0 veya 2.5)', max_digits=10, verbose_name='Soru Puanı'),
        ),
    ]
