# Generated by Django 4.2.29 on 2026-03-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_uploadsession_points_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('INSTRUCTOR', 'Öğretim Elemanı'), ('COORDINATOR', 'Koordinatör'), ('ASSISTANT', 'Araştırma Görevlisi / Asistan'), ('ADMIN', 'Yönetici')], default='INSTRUCTOR', max_length=20, verbose_name='Rol'),
        ),
    ]
