# Generated by Django 4.2.29 on 2026-03-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0015_faz12_exam_template'),
        ('grading', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='test_form',
            field=models.ForeignKey(blank=True, help_text='Bu yükleme hangi test formunun değerlendirmesi için?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='itempool.testform', verbose_name='İlişkili Test Formu'),
        ),
    ]
