# Generated by Django 4.2.29 on 2026-04-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0026_examtemplate_footer_css_and_more'),
        ('grading', '0008_userprofile_theme_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='exam_application',
            field=models.ForeignKey(blank=True, help_text='Bu yükleme hangi sınav uygulamasına ait?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='itempool.examapplication', verbose_name='Sınav Uygulaması'),
        ),
    ]
