# Generated by Django 4.2.29 on 2026-03-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(verbose_name='Madde Kökü (Soru)')),
                ('item_type', models.CharField(choices=[('MCQ', 'Çoktan Seçmeli'), ('TF', 'Doğru-Yanlış'), ('MATCHING', 'Eşleştirme'), ('OPEN', 'Açık Uçlu')], default='MCQ', max_length=20, verbose_name='Soru Tipi')),
                ('difficulty_intended', models.CharField(choices=[('EASY', 'Kolay'), ('MEDIUM', 'Orta'), ('HARD', 'Zor')], default='MEDIUM', max_length=20, verbose_name='Hedeflenen Zorluk')),
                ('version', models.IntegerField(default=1, verbose_name='Sürüm')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('RETIRED', 'Emekli/Kullanımdan Kaldırılmış')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_items', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Madde',
                'verbose_name_plural': 'Maddeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Havuz Adı')),
                ('course', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('semester', models.CharField(help_text='Örn: 2024-Güz', max_length=20, verbose_name='Dönem')),
                ('level', models.CharField(help_text='Örn: Lisans 1, Yüksek Lisans', max_length=20, verbose_name='Eğitim Düzeyi')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiketler')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('ARCHIVED', 'Arşivlendi')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pools', to=settings.AUTH_USER_MODEL, verbose_name='Havuz Sahibi')),
            ],
            options={
                'verbose_name': 'Madde Havuzu',
                'verbose_name_plural': 'Madde Havuzları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Örn: ÖÇ1, KAZ1', max_length=20, verbose_name='Çıktı Kodu')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('level', models.CharField(choices=[('KNOWLEDGE', 'Bilgi'), ('COMPREHENSION', 'Kavrama'), ('APPLICATION', 'Uygulama'), ('ANALYSIS', 'Analiz'), ('SYNTHESIS', 'Sentez'), ('EVALUATION', 'Değerlendirme')], default='KNOWLEDGE', max_length=30, verbose_name='Bilişsel Düzey (Bloom)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Ağırlık (%)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'Öğrenme Çıktısı',
                'verbose_name_plural': 'Öğrenme Çıktıları',
                'ordering': ['pool', 'order', 'code'],
                'unique_together': {('pool', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fork', models.BooleanField(default=False, verbose_name='Kopyalandı (Forked)')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_item_instances', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen Kullanıcı')),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='itempool.iteminstance', verbose_name='Kaynak Madde Bağlantısı')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='itempool.item', verbose_name='Madde')),
                ('learning_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='itempool.learningoutcome', verbose_name='Öğrenme Çıktısı (Kazanım)')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_instances', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'Havuzdaki Madde',
                'verbose_name_plural': 'Havuzdaki Maddeler',
                'ordering': ['pool', '-added_at'],
                'unique_together': {('pool', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ItemChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Örn: A, B, C, D, E', max_length=5, verbose_name='Seçenek Etiketi')),
                ('text', models.TextField(verbose_name='Seçenek Metni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru Cevap mı?')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='itempool.item', verbose_name='Madde')),
            ],
            options={
                'verbose_name': 'Madde Seçeneği',
                'verbose_name_plural': 'Madde Seçenekleri',
                'ordering': ['item', 'order', 'label'],
                'unique_together': {('item', 'label')},
            },
        ),
    ]
