# Generated by Django 4.2.29 on 2026-03-04 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('uploaded_file', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='Yüklenen Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata Oluştu')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('item_count', models.IntegerField(default=0, verbose_name='Madde Sayısı')),
                ('error_count', models.IntegerField(default=0, verbose_name='Hata Sayısı')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'İçe Aktarma Grubu',
                'verbose_name_plural': 'İçe Aktarma Grupları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(verbose_name='Madde Kökü')),
                ('choices_json', models.JSONField(verbose_name='Şıklar (JSON)')),
                ('correct_answer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Doğru Cevap')),
                ('manual_review', models.BooleanField(default=False, verbose_name='Manuel İnceleme Gerekli')),
                ('review_note', models.TextField(blank=True, null=True, verbose_name='İnceleme Notu')),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_items', to='itempool.importbatch', verbose_name='Yükleme Grubu')),
            ],
            options={
                'verbose_name': 'Taslak Madde',
                'verbose_name_plural': 'Taslak Maddeler',
            },
        ),
    ]
