# Generated by Django 4.2.29 on 2026-03-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0002_importbatch_draftitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftitem',
            name='ai_suggestions',
            field=models.JSONField(blank=True, null=True, verbose_name='AI Önerileri'),
        ),
    ]
