# Generated by Django 4.2.29 on 2026-03-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0003_draftitem_ai_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Güven Skoru (0-1)')),
                ('reasoning', models.TextField(blank=True, null=True, verbose_name='AI Gerekçesi')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_suggestions', to='itempool.item', verbose_name='Madde')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='itempool.learningoutcome', verbose_name='Önerilen Çıktı')),
            ],
            options={
                'verbose_name': 'Çıktı Önerisi',
                'verbose_name_plural': 'Çıktı Önerileri',
                'ordering': ['-score'],
            },
        ),
    ]
