# Generated by Django 4.2.29 on 2026-03-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0004_outcomesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftitem',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itempool.learningoutcome', verbose_name='Öğrenme Çıktısı'),
        ),
    ]
