# Generated by Django 4.2.29 on 2026-03-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0005_draftitem_learning_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftitem',
            name='learning_outcome',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='learning_outcome',
        ),
        migrations.AddField(
            model_name='draftitem',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, to='itempool.learningoutcome', verbose_name='Öğrenme Çıktıları'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='assigned_items', to='itempool.learningoutcome', verbose_name='Öğrenme Çıktıları (Kazanımlar)'),
        ),
    ]
