# Generated by Django 4.2.29 on 2026-03-04 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0006_remove_draftitem_learning_outcome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_form_id', models.IntegerField(blank=True, null=True, verbose_name='Sınav Form ID')),
                ('difficulty_p', models.FloatField(default=0.0, verbose_name='Zorluk İndeksi (p)')),
                ('discrimination_r', models.FloatField(default=0.0, verbose_name='Ayırt Edicilik (r)')),
                ('distractor_efficiency', models.FloatField(default=0.0, verbose_name='Çeldirici Verimliliği')),
                ('flagged', models.BooleanField(default=False, verbose_name='Sorunlu Madde mi?')),
                ('risk_score', models.IntegerField(default=0, verbose_name='Risk Skoru (0-100)')),
                ('analysis_data_json', models.JSONField(default=dict, verbose_name='Detaylı Analiz Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='itempool.iteminstance', verbose_name='Madde Kaydı')),
            ],
            options={
                'verbose_name': 'Madde Analiz Sonucu',
                'verbose_name_plural': 'Madde Analiz Sonuçları',
                'ordering': ['-created_at'],
            },
        ),
    ]
