# Generated by Django 4.2.29 on 2026-03-04 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0007_itemanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Form Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('APPLIED', 'Uygulandı'), ('ARCHIVED', 'Arşivlendi')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_metadata', models.JSONField(blank=True, default=dict, verbose_name='Oluşturma Kuralları')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_forms', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'Test Formu',
                'verbose_name_plural': 'Test Formları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tablo Adı')),
                ('rows_json', models.JSONField(verbose_name='Tablo Verisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_tables', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'Belirtke Tablosu',
                'verbose_name_plural': 'Belirtke Tabloları',
            },
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Blueprint Adı')),
                ('distribution_json', models.JSONField(verbose_name='Çıktı Dağılımı')),
                ('total_items', models.PositiveIntegerField(verbose_name='Toplam Soru Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='itempool.itempool', verbose_name='Havuz')),
            ],
            options={
                'verbose_name': 'Blueprint / Şablon',
                'verbose_name_plural': 'Blueprints / Şablonlar',
            },
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Soru Sırası')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puan')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='itempool.testform', verbose_name='Form')),
                ('item_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_usage', to='itempool.iteminstance', verbose_name='Madde')),
            ],
            options={
                'verbose_name': 'Form Maddesi',
                'verbose_name_plural': 'Form Maddeleri',
                'ordering': ['order'],
                'unique_together': {('form', 'item_instance')},
            },
        ),
    ]
