# Generated by Django 4.2.29 on 2026-03-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0008_testform_specificationtable_blueprint_formitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemanalysisresult',
            name='test_form_id',
        ),
        migrations.AddField(
            model_name='itemanalysisresult',
            name='test_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_analysis_results', to='itempool.testform', verbose_name='Sınav Formu'),
        ),
    ]
