# Generated by Django 4.2.29 on 2026-03-04 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0009_remove_itemanalysisresult_test_form_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('VIEWER', 'Görüntüleyebilir'), ('EDITOR', 'Düzenleyebilir'), ('MANAGER', 'Yönetebilir (Silme/Yetki Verme)')], default='VIEWER', max_length=20, verbose_name='Yetki Seviyesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='itempool.itempool', verbose_name='Havuz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Havuz Yetkisi',
                'verbose_name_plural': 'Havuz Yetkileri',
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
