# Generated by Django 4.2.29 on 2026-03-04 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0010_poolpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Eylem')),
                ('details_json', models.JSONField(blank=True, default=dict, verbose_name='Değişiklik Detayları')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='itempool.item', verbose_name='Madde')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Madde İşlem Kaydı',
                'verbose_name_plural': 'Madde İşlem Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
