# Generated by Django 4.2.29 on 2026-03-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_userprofile_role'),
        ('itempool', '0011_itemauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemanalysisresult',
            name='upload_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_analysis_results', to='grading.uploadsession', verbose_name='Yükleme Oturumu'),
        ),
    ]
