# Generated by Django 4.2.29 on 2026-03-21 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0012_itemanalysisresult_upload_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expected_answer',
            field=models.TextField(blank=True, help_text='Kısa cevaplı sorular için kabul edilebilir cevap(lar)', null=True, verbose_name='Beklenen Cevap'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_choices',
            field=models.IntegerField(default=4, help_text='Çoktan seçmeli sorular için 2-10 arası seçenek sayısı', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Seçenek Sayısı'),
        ),
        migrations.AddField(
            model_name='item',
            name='scoring_rubric',
            field=models.TextField(blank=True, help_text='Açık uçlu sorular için puanlama kriterleri', null=True, verbose_name='Puanlama Kılavuzu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MCQ', 'Çoktan Seçmeli'), ('TF', 'Doğru-Yanlış'), ('SHORT_ANSWER', 'Kısa Cevaplı'), ('OPEN', 'Açık Uçlu'), ('MATCHING', 'Eşleştirme')], default='MCQ', max_length=20, verbose_name='Soru Tipi'),
        ),
    ]
