# Generated by Django 4.2.29 on 2026-03-21 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0013_faz10_item_model_genisletme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Bilgisayar Müh. 2024-Güz Grup A', max_length=200, verbose_name='Grup Adı')),
                ('course', models.CharField(help_text='Bu grubun aldığı ders', max_length=200, verbose_name='Ders')),
                ('semester', models.CharField(help_text='Örn: 2024-Güz', max_length=100, verbose_name='Dönem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Öğrenci Grubu',
                'verbose_name_plural': 'Öğrenci Grupları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateField(verbose_name='Uygulama Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applications', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to='itempool.studentgroup', verbose_name='Öğrenci Grubu')),
                ('test_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='itempool.testform', verbose_name='Test Formu')),
            ],
            options={
                'verbose_name': 'Sınav Uygulaması',
                'verbose_name_plural': 'Sınav Uygulamaları',
                'ordering': ['-applied_at'],
                'unique_together': {('test_form', 'group')},
            },
        ),
    ]
