# Generated by Django 4.2.29 on 2026-03-21 23:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0014_faz11_student_group_exam_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('is_default', models.BooleanField(default=False, help_text='Seçilirse bu şablon varsayılan olarak kullanılır', verbose_name='Varsayılan Şablon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210×297 mm)'), ('A5', 'A5 (148×210 mm)'), ('LETTER', 'Letter (216×279 mm)')], default='A4', max_length=20, verbose_name='Kağıt Boyutu')),
                ('column_count', models.IntegerField(default=1, help_text='1, 2 veya 3 sütun', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Sütun Sayısı')),
                ('column_divider', models.BooleanField(default=True, verbose_name='Sütunlar Arası Çizgi')),
                ('margin_top', models.IntegerField(default=25, verbose_name='Üst Kenar Boşluğu (mm)')),
                ('margin_bottom', models.IntegerField(default=25, verbose_name='Alt Kenar Boşluğu (mm)')),
                ('margin_left', models.IntegerField(default=20, verbose_name='Sol Kenar Boşluğu (mm)')),
                ('margin_right', models.IntegerField(default=20, verbose_name='Sağ Kenar Boşluğu (mm)')),
                ('font_family', models.CharField(choices=[('Times New Roman, serif', 'Times New Roman'), ('Arial, sans-serif', 'Arial'), ('Helvetica, sans-serif', 'Helvetica'), ('Georgia, serif', 'Georgia'), ('Calibri, sans-serif', 'Calibri')], default='Times New Roman, serif', max_length=100, verbose_name='Font')),
                ('font_size', models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(16)], verbose_name='Font Boyutu (pt)')),
                ('question_spacing', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(30)], verbose_name='Sorular Arası Boşluk (pt)')),
                ('choice_layout', models.CharField(choices=[('vertical', 'Dikey (alt alta)'), ('horizontal', 'Yatay (yan yana)')], default='vertical', max_length=20, verbose_name='Seçenek Dizilimi')),
                ('header_left', models.CharField(blank=True, help_text='Örn: Kurum adı. {course}, {semester}, {date} değişkenlerini kullanabilirsiniz.', max_length=300, verbose_name='Üst Bilgi (Sol)')),
                ('header_center', models.CharField(blank=True, help_text='Örn: {form_name}', max_length=300, verbose_name='Üst Bilgi (Orta)')),
                ('header_right', models.CharField(blank=True, help_text='Örn: Tarih: {date}', max_length=300, verbose_name='Üst Bilgi (Sağ)')),
                ('show_header_line', models.BooleanField(default=True, verbose_name='Üst Bilgi Altına Çizgi')),
                ('footer_left', models.CharField(blank=True, max_length=300, verbose_name='Alt Bilgi (Sol)')),
                ('footer_center', models.CharField(blank=True, help_text='Örn: Sayfa {page}/{total_pages}', max_length=300, verbose_name='Alt Bilgi (Orta)')),
                ('footer_right', models.CharField(blank=True, max_length=300, verbose_name='Alt Bilgi (Sağ)')),
                ('show_footer_line', models.BooleanField(default=True, verbose_name='Alt Bilgi Üstüne Çizgi')),
                ('show_student_info_box', models.BooleanField(default=True, help_text='Ad Soyad, No, Tarih için boş alan', verbose_name='Öğrenci Bilgi Kutusu')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sınav Kağıdı Şablonu',
                'verbose_name_plural': 'Sınav Kağıdı Şablonları',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
