# Generated by Django 4.2.29 on 2026-03-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0015_faz12_exam_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempool',
            name='course',
        ),
        migrations.RemoveField(
            model_name='itempool',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='testform',
            name='pool',
        ),
        migrations.AddField(
            model_name='itempool',
            name='description',
            field=models.TextField(blank=True, help_text='Havuzun hangi konu veya aşanlara ait olduğunu açıklayın', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='itempool',
            name='level',
            field=models.CharField(blank=True, help_text='Örn: Lisans 1, Yüksek Lisans', max_length=20, verbose_name='Eğitim Düzeyi'),
        ),
    ]
