# Generated by Django 4.2.29 on 2026-04-05 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itempool', '0017_faz17_course_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Örn: EPD 201', max_length=50, verbose_name='Ders Kodu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Örn: Eğitim Psikolojisi', max_length=200, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pools',
            field=models.ManyToManyField(blank=True, help_text='Bu derste kullanılacak madde havuzları', related_name='courses', to='itempool.itempool', verbose_name='Bağlı Madde Havuzları'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(help_text='Örn: 2026-Güz', max_length=100, verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='coursespectable',
            name='name',
            field=models.CharField(help_text='Örn: Vize Belirtke Tablosu', max_length=255, verbose_name='Tablo Adı'),
        ),
        migrations.AlterField(
            model_name='examapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to='itempool.course', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='examapplication',
            name='test_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='itempool.testform', verbose_name='Sınav Formu'),
        ),
    ]
