# Generated by Django 4.2.29 on 2026-04-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0018_alter_course_code_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='Gemini embedding modelinden gelen sayısal dizi', verbose_name='Vektör Verisi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='itempool.item', verbose_name='Madde')),
            ],
            options={
                'verbose_name': 'Madde Vektörü',
                'verbose_name_plural': 'Madde Vektörleri',
            },
        ),
    ]
