# Generated by Django 4.2.29 on 2026-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0019_itemembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='choice_overrides',
            field=models.JSONField(blank=True, null=True, verbose_name='Şık Düzenlemeleri'),
        ),
    ]
