# Generated by Django 4.2.29 on 2026-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0020_formitem_choice_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='header_html',
            field=models.TextField(blank=True, help_text='Word dosyasından dönüştürülen karmaşık başlık içeriği', null=True, verbose_name='Özel Başlık (HTML)'),
        ),
    ]
