# Generated by Django 4.2.29 on 2026-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0021_examtemplate_header_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtemplate',
            name='choice_layout',
            field=models.CharField(choices=[('vertical', 'Dikey (alt alta)'), ('horizontal', 'Yatay (yan yana)'), ('auto', 'Otomatik (Uzunluğa göre)')], default='vertical', max_length=20, verbose_name='Seçenek Dizilimi'),
        ),
    ]
