# Generated by Django 4.2.29 on 2026-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0022_alter_examtemplate_choice_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='show_question_points',
            field=models.BooleanField(default=True, help_text='Her sorunun yanında puanını göster', verbose_name='Soru Puanlarını Göster'),
        ),
    ]
