# Generated by Django 4.2.29 on 2026-04-05 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0023_examtemplate_show_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='choice_spacing',
            field=models.IntegerField(default=2, help_text='Şıklar arasındaki dikey boşluk', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Seçenek Aralığı (pt)'),
        ),
    ]
