# Generated by Django 4.2.29 on 2026-04-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0024_examtemplate_choice_spacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='footer_html',
            field=models.TextField(blank=True, help_text='Zengin metin editörü ile oluşturulan alt bilgi içeriği', null=True, verbose_name='Özel Alt Bilgi (HTML)'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='header_html',
            field=models.TextField(blank=True, help_text='Zengin metin editörü veya Word dosyasından aktarılan başlık içeriği', null=True, verbose_name='Özel Başlık (HTML)'),
        ),
    ]
