# Generated by Django 4.2.29 on 2026-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0025_examtemplate_footer_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='footer_css',
            field=models.TextField(blank=True, help_text='GrapesJS tarafından üretilen CSS', null=True, verbose_name='Alt Bilgi CSS'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='footer_design_json',
            field=models.JSONField(blank=True, help_text='GrapesJS editör durumu (JSON)', null=True, verbose_name='Alt Bilgi Tasarım Verisi'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='header_css',
            field=models.TextField(blank=True, help_text='GrapesJS tarafından üretilen CSS', null=True, verbose_name='Üst Bilgi CSS'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='header_design_json',
            field=models.JSONField(blank=True, help_text='GrapesJS editör durumu (JSON)', null=True, verbose_name='Üst Bilgi Tasarım Verisi'),
        ),
    ]
