# Generated by Django 4.2.30 on 2026-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0026_examtemplate_footer_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Kod içerisinden bu prompt'u çağırmak için kullanılacak benzersiz isim (örn: ITEM_GENERATE).", max_length=100, unique=True, verbose_name='Kısa Kod (Slug)')),
                ('name', models.CharField(max_length=200, verbose_name='Prompt Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama/Kullanım Amacı')),
                ('system_instruction', models.TextField(blank=True, help_text="Modelin kişiliğini ve genel davranış kurallarını belirler (örn: 'Sen bir fizik öğretmenisin').", verbose_name='Sistem Talimatı (System Instruction)')),
                ('template', models.TextField(help_text="Değişkenleri süslü parantez içinde belirtin. Örn: 'Aşağıdaki soruyu incele: {stem}'", verbose_name='Prompt Şablonu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Şablonu',
                'verbose_name_plural': 'AI Prompt Şablonları',
                'ordering': ['name'],
            },
        ),
    ]
