# Generated by Django 4.2.30 on 2026-04-10 08:39

from django.db import migrations


def seed_prompts(apps, schema_editor):
    AIPrompt = apps.get_model('itempool', 'AIPrompt')
    
    prompts = [
        {
            'slug': 'ITEM_IMPROVE',
            'name': 'Madde İyileştirme',
            'description': 'Mevcut bir soruyu dil bilgisi ve netlik açısından iyileştirmek için kullanılır.',
            'system_instruction': 'Sen deneyimli bir ölçme ve değerlendirme uzmanısın.',
            'template': """Aşağıdaki sınav sorusunu dil bilgisi, netlik ve bilimsel doğruluk açısından incele. 
Gerekirse madde kökünü (soruyu) ve şıkları iyileştir.

Soru: {stem}
Şıklar: {choices}

Lütfen sadece iyileştirilmiş versiyonu JSON formatında dön:
{{"improved_stem": "...", "improved_choices": [...]}}"""
        },
        {
            'slug': 'SUGGEST_OUTCOMES',
            'name': 'Kazanım Önerisi',
            'description': 'Bir maddeye en uygun öğrenme çıktısını eşleştirmek için kullanılır.',
            'system_instruction': 'Sen bir eğitim programı uzmanısın.',
            'template': """Aşağıdaki soruya en uygun öğrenme çıktısını seç.

Soru: {stem}

Öğrenme Çıktıları Listesi:
{outcomes_text}

Lütfen en uygun çıktının ID'sini, güven skorunu (0-1 arası) ve kısa gerekçesini JSON olarak dön:
{{"outcome_id": ..., "score": ..., "reason": "..."}}"""
        },
        {
            'slug': 'ITEM_GENERATE',
            'name': 'Madde Üretimi',
            'description': 'Kazanım bazlı yeni soru üretmek için kullanılır.',
            'system_instruction': 'Sen profesyonel bir soru yazarısın.',
            'template': """Aşağıdaki öğrenme çıktısına (kazanıma) ve zorluk seviyesine uygun, {count_str}profesyonel sınav sorusu üret.

Öğrenme Çıktısı: {outcome_text}
Bloom Düzeyi: {bloom_level} ({guidance})
Zorluk Seviyesi: {difficulty}
Soru Tipi: {item_type}

Kalite Kuralları:
1. Türkçe imla kurallarına tam uyum.
2. Bilimsel doğruluk ve netlik.
3. Çeldiriciler mantıklı ve birbirine yakın uzunlukta olmalı.
4. "Hepsi" veya "Hiçbiri" gibi kaçamak şıklardan kaçın.
5. Madde kökünde olumsuz ifade varsa ("değildir", "olamaz" vb.) BÜYÜK harfle yaz.

Lütfen cevabı SADECE aşağıdaki JSON formatında dön:
{format_str}"""
        },
        {
            'slug': 'SUGGEST_DISTRACTORS',
            'name': 'Çeldirici Önerisi',
            'description': 'Sorunun doğru cevabına alternatif çeldiriciler üretir.',
            'system_instruction': 'Sen bir ölçme ve değerlendirme uzmanısın.',
            'template': """Aşağıdaki soru kökü ve doğru cevap için 3 adet mantıklı çeldirici (yanlış şık) üret.

Soru: {stem}
Doğru Cevap: {correct_answer}

Lütfen SADECE şu formatta bir JSON listesi dön:
["Çeldirici 1", "Çeldirici 2", "Çeldirici 3"]"""
        },
        {
            'slug': 'GENERATE_VARIATION',
            'name': 'Madde Varyasyonu Üretimi',
            'description': 'Mevcut bir sorunun benzer versiyonunu üretir.',
            'system_instruction': 'Sen bir soru bankası editörüsün.',
            'template': """Aşağıdaki sınav sorusunun anlamsal olarak benzer ancak farklı bir versiyonunu üret (sayıları veya örnekleri değiştirerek).

Orijinal Soru: {stem}
Orijinal Şıklar: {choices}

Lütfen cevabı SADECE aşağıdaki JSON formatında dön:
{{
    "stem": "Yeni soru kökü",
    "choices": [
        {{"label": "A", "text": "Yeni Seçenek A"}},
        ...
    ],
    "correct_answer": "..."
}}"""
        }
    ]
    
    for p_data in prompts:
        AIPrompt.objects.get_or_create(slug=p_data['slug'], defaults=p_data)

class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0027_aiprompt'),
    ]

    operations = [
        migrations.RunPython(seed_prompts),
    ]
