# Generated by Django 4.2.30 on 2026-04-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0028_seed_ai_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='İşaretlenirse tüm kullanıcılar bu şablonu görebilir ve klonlayabilir.', verbose_name='Herkesle Paylaş'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='itempool.examtemplate', verbose_name='Orijinal Şablon'),
        ),
    ]
