# Generated by Django 4.2.30 on 2026-05-24 06:49

from django.db import migrations, models


def migrate_bloom_levels(apps, schema_editor):
    LearningOutcome = apps.get_model('itempool', 'LearningOutcome')
    
    # Eski değerler -> Yeni değerler eşleşmesi
    mapping = {
        'KNOWLEDGE': 'REMEMBERING',
        'COMPREHENSION': 'UNDERSTANDING',
        'APPLICATION': 'APPLYING',
        'ANALYSIS': 'ANALYZING',
        'SYNTHESIS': 'EVALUATING',
        'EVALUATION': 'CREATING',
    }
    
    for outcome in LearningOutcome.objects.all():
        old_level = outcome.level
        if old_level in mapping:
            outcome.level = mapping[old_level]
            outcome.save()


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0029_examtemplate_is_shared_examtemplate_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='subject',
            field=models.CharField(blank=True, help_text='Öğrenme çıktısının ait olduğu konu veya ünite', max_length=200, verbose_name='İçerik / Konu'),
        ),
        migrations.RunPython(migrate_bloom_levels, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='learningoutcome',
            name='level',
            field=models.CharField(choices=[('REMEMBERING', 'Hatırlama'), ('UNDERSTANDING', 'Anlama'), ('APPLYING', 'Uygulama'), ('ANALYZING', 'Analiz Etme'), ('EVALUATING', 'Değerlendirme'), ('CREATING', 'Yaratma')], default='REMEMBERING', max_length=30, verbose_name='Bilişsel Düzey (Bloom)'),
        ),
    ]

