# Generated by Django 4.2.30 on 2026-08-06 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0030_learningoutcome_subject_alter_learningoutcome_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AddField(
            model_name='testform',
            name='booklet_code',
            field=models.CharField(default='A', help_text='Örn: A, B, C, D', max_length=10, verbose_name='Kitapçık Kodu'),
        ),
        migrations.AddField(
            model_name='testform',
            name='parent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='itempool.testform', verbose_name='Ana Sınav Formu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('NEEDS_REVISION', 'Revizyon Gerektiriyor'), ('RETIRED', 'Emekli/Kullanımdan Kaldırılmış')], default='DRAFT', max_length=20, verbose_name='Durum'),
        ),
    ]
