# Generated by Django 4.2.30 on 2026-08-06

from django.db import migrations

BAUN_LOGO_SVG = '''<svg width="70" height="70" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="46" fill="#0f7b88" />
  <circle cx="50" cy="50" r="40" fill="none" stroke="#ffffff" stroke-width="2" />
  <path d="M 30 55 Q 50 42 70 55 Q 50 64 30 55 Z" fill="#ffffff"/>
  <circle cx="50" cy="40" r="6" fill="#ffffff"/>
  <path d="M 35 62 Q 50 70 65 62" stroke="#ffffff" stroke-width="2.5" fill="none"/>
  <polygon points="50,15 53,22 60,22 55,26 57,33 50,29 43,33 45,26 40,22 47,22" fill="#ffffff" />
</svg>'''


NEF_LOGO_SVG = '''<svg width="70" height="70" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <circle cx="50" cy="50" r="46" fill="#b84c7d" />
  <circle cx="50" cy="50" r="40" fill="none" stroke="#ffffff" stroke-width="2" />
  <path d="M 30 55 Q 50 42 70 55 Q 50 64 30 55 Z" fill="#ffffff"/>
  <circle cx="50" cy="40" r="6" fill="#ffffff"/>
  <path d="M 35 62 Q 50 70 65 62" stroke="#ffffff" stroke-width="2.5" fill="none"/>
  <polygon points="50,15 53,22 60,22 55,26 57,33 50,29 43,33 45,26 40,22 47,22" fill="#ffffff" />
</svg>'''


def _make_nef_header_html():
    return f'''<table width="100%" style="border-collapse:collapse; font-family:Arial, sans-serif; margin-bottom:4px;">
<tr>
<td style="width:18%; text-align:left; vertical-align:middle;">
{BAUN_LOGO_SVG}
</td>
<td style="width:64%; text-align:center; vertical-align:middle;">
<div style="font-size:13pt; font-weight:bold; color:#000; letter-spacing:0.3px; line-height:1.2;">BALIKESİR ÜNİVERSİTESİ NECATİBEY EĞİTİM FAKÜLTESİ</div>
<div style="font-size:12pt; font-weight:bold; color:#000; margin-top:4px;">{{semester}} Yarıyıl Sonu Sınavı</div>
</td>
<td style="width:18%; text-align:right; vertical-align:middle;">
{NEF_LOGO_SVG}
<div style="font-size:10pt; font-weight:bold; color:#000; margin-top:2px;">{{date}}</div>
</td>
</tr>
</table>
<table width="100%" style="border-collapse:collapse; font-family:Arial, sans-serif; font-size:9.5pt; color:#000; margin-top:6px; line-height:1.5;">
<tr>
<td style="text-align:left;">
<strong>Ders Kodu ve Adı:</strong> <span style="font-weight:bold;">{{course_code}} {{course}}</span>
</td>
<td style="text-align:right;">
<strong>Ders Sorumlusu:</strong> <span style="font-weight:bold;">{{teacher_name}}</span>
</td>
</tr>
<tr>
<td colspan="2" style="padding-top:4px;">
<table width="100%" style="border-collapse:collapse; font-size:9.5pt;">
<tr>
<td style="text-align:left; width:45%;">
<strong>Öğrenci Adı Soyadı:</strong> <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u>
</td>
<td style="text-align:center; width:35%;">
<strong>Numarası:</strong> <u>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</u>
</td>
<td style="text-align:right; width:20%;">
<strong>S ü r e :</strong> 3 0 &nbsp; d k
</td>
</tr>
</table>
</td>
</tr>
</table>
<div style="border-bottom:2px solid #000; margin-top:6px; margin-bottom:10px;"></div>'''


def seed_nef_template(apps, schema_editor):
    ExamTemplate = apps.get_model('itempool', 'ExamTemplate')

    # Diğer şablonların varsayılan durumunu güncelle ve NEF şablonunu varsayılan yap
    ExamTemplate.objects.filter(is_default=True, created_by=None).update(is_default=False)

    ExamTemplate.objects.update_or_create(
        name='Necatibey Eğitim Fakültesi (Kurumsal)',
        defaults={
            'is_default': True,
            'is_shared': True,
            'column_count': 1,
            'column_divider': False,
            'font_family': 'Arial, sans-serif',
            'font_size': 10,
            'question_spacing': 12,
            'choice_layout': 'vertical',
            'header_html': _make_nef_header_html(),
            'footer_html': '<div style="text-align:center;font-size:9pt;color:#666;">{page} / {total_pages}</div>',
            'show_student_info_box': False,
            'show_header_line': False,
            'show_footer_line': True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0031_alter_course_options_testform_booklet_code_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_nef_template),
    ]
