# Generated by Django 4.2.30 on 2026-08-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itempool', '0032_seed_nef_exam_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftitem',
            name='learning_outcomes',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='learning_outcomes',
        ),
        migrations.AddField(
            model_name='draftitem',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itempool.learningoutcome', verbose_name='Öğrenme Çıktısı'),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to='itempool.learningoutcome', verbose_name='Öğrenme Çıktısı (Kazanım)'),
        ),
    ]
